spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: ${BOT_DATASOURCE_URL}
    username: ${BOT_DATASOURCE_USERNAME}
    password: ${BOT_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:target/classes/db/migration