package io.vaku.model.enm;

public enum UserStatus {
    REQUIRE_REGISTRATION,
    REQUIRE_PASSWORD,
    REQUIRE_ROLE,
    REQUIRE_NAME,
    REQUIRE_BIRTHDATE,
    REQUIRE_ROOM,
    REQUIRE_BIO,
    REQUIRE_PHOTO,
    REQUIRE_QUESTION_1,
    REQUIRE_QUESTION_2,
    REQUIRE_VALUES_CONFIRM,
    REQUIRE_RULES_CONFIRM,
    REGISTERED,
    BLOCKED
}
